version: "3.1"
services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 8003:8025
      - 1025:1025

  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 8001:1234
    environment:
      - HOST=0.0.0.0
    depends_on:
      - mongo
    links:
      - mongo

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./.docker/metabase-data:/metabase-data
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: develop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGODB_USER=mongo
      - MONGODB_PASS=secret
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.docker/mongodb:/data/db
    ports:
      - 27017:27017

  redmin:
    image: sasanrose/phpredmin
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
      - PHPREDMIN_AUTH_USERNAME=root
      - PHPREDMIN_AUTH_PASSWORD=secret
    ports:
      - "8002:80"
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis:/data
